### DISCUSSION TITLE
Sample YAML generated from spreadsheets

### DISCUSSION THREAD

**Discussion by gerrycampion** [cdisc-org/rule-transformations#5] [Show and tell]
@htu has provided the following samples for review

CG0001
```yaml
changed: '2023-03-14T19:24:17Z'
content: example-content
created: '2021-09-28T16:27:29Z'
creator:
  id: dd0f9aa3-68f9-4825-84a4-86c8303daaff
id: 120af9b1-1db7-4e11-a126-3ac265103fa9
json:
  Authorities:
  - Organization: CDISC
    Standards:
    - Name: SDTMIG
      References:
      - Citations:
        - Cited_Guidance: Check the CDISC Controlled Terminology [see Appendix C -
            Controlled Terminology] for reserved two-character domain identifiers
            or abbreviations. If one has not been assigned by CDISC, then the sponsor
            may select the unique two-character domain code to be used consistently
            throughout the submission.
          Document: IG v3.2
          Item: 3.d
          Section: '2.6'
        Origin: SDTM and SDTMIG Conformance Rules
        Rule_Identifier:
          Id: CG0001
          Version: '1'
        Version: '2.0'
      Version: '3.2'
    - Name: SDTMIG
      References:
      - Citations:
        - Cited_Guidance: Determine the domain code, one that is not a domain code
            in the CDISC Controlled Terminology codelist "SDTM Domain Abbreviations"
            available at http://www.cancer.gov/research/resources/terminology/cdisc.
            If it desired to have this domain code as part of CDISC controlled terminology,
            then submit a request to https://ncitermform.nci.nih.gov/ncitermform/?version=cdisc.
            The sponsor-selected, two-character domain code should be used consistently
            throughout the submission.
          Document: IG v3.3
          Item: 3.e
          Section: '2.6'
        Origin: SDTM and SDTMIG Conformance Rules
        Rule_Identifier:
          Id: CG0001
          Version: '1'
        Version: '2.0'
      Version: '3.3'
    - Name: SDTMIG
      References:
      - Citations:
        - Cited_Guidance: Using SDTM-specified standard domain names and prefixes
            where applicable
          Document: IG v3.4
          Item: ''
          Section: 3.2.2
        Origin: SDTM and SDTMIG Conformance Rules
        Rule_Identifier:
          Id: CG0001
          Version: '1'
        Version: '2.0'
      Version: '3.4'
  Check:
    Check: null
  Core:
    Id: CDISC.SDTMIG.CG0001
    Status: Draft
    Version: '1'
  Description: Trigger error when DOMAIN not equal to valid Domain Code published
    by CDISC
  Executability: null
  Outcome:
    Message: DOMAIN not equal to valid Domain Code published by CDISC
  Rule_Type: Record Data
  Scope:
    Classes:
      Include:
      - ALL
    Domains:
      Include:
      - ALL
  Sensitivity: Record
```

CG0373
```yaml
changed: '2023-03-14T19:38:05Z'
content: example-content
created: '2021-11-06T09:44:41Z'
creator:
  id: dd0f9aa3-68f9-4825-84a4-86c8303daaff
id: abcffc09-b50f-46a2-bea0-0baba8d3e3c1
json:
  Authorities:
  - Organization: CDISC
    Standards:
    - Name: SDTMIG
      References:
      - Citations:
        - Cited_Guidance: There is a one-to-one correspondence between a domain dataset
            and it's Supplemental Qualifier dataset by creating one SUPPQUAL for each
            domain dataset. The single SUPPQUAL dataset option that was introduced
            in SDTMIG v3.1.1 is now deprecated. The set of Supplemental Qualifiers
            for each domain is included in a separate dataset with the name SUPP--
            where '--' denotes the source domain which the supplemental Qualifiers
            relate back to.
          Document: IG v3.2
          Item: ''
          Section: 8.4.2
        Origin: SDTM and SDTMIG Conformance Rules
        Rule_Identifier:
          Id: CG0373
          Version: '1'
        Version: '2.0'
      Version: '3.2'
    - Name: SDTMIG
      References:
      - Citations:
        - Cited_Guidance: There is a one-to-one correspondence between a domain dataset
            and its Supplemental Qualifier dataset. The single SUPPQUAL dataset option
            that was introduced in SDTMIG v3.1 was deprecated. The set of Supplemental
            Qualifiers for each domain is included in a separate dataset with the
            name SUPP-- where "--" denotes the source domain which the Supplemental
            Qualifiers relate back to.
          Document: IG v3.3
          Item: ''
          Section: 8.4.2
        Origin: SDTM and SDTMIG Conformance Rules
        Rule_Identifier:
          Id: CG0373
          Version: '1'
        Version: '2.0'
      Version: '3.3'
    - Name: SDTMIG
      References:
      - Citations:
        - Cited_Guidance: "There is a one-to-one correspondence between a domain dataset\
            \ and it's Supplemental Qualifier dataset by creating one SUPPQUAL for\
            \ each domain dataset. The single SUPPQUAL dataset option that was introduced\
            \ in SDTMIG v3.1.1 is now deprecated.  The set of Supplemental Qualifiers\
            \ for each domain is included in a separate dataset with the name SUPP--\
            \ where \u201C--\u201C denotes the source domain which the supplemental\
            \ Qualifiers relate back to."
          Document: IG v3.2
          Item: ''
          Section: 8.4.2
        Origin: SDTM and SDTMIG Conformance Rules
        Rule_Identifier:
          Id: CG0373
          Version: '1'
        Version: '2.0'
      Version: '3.4'
  Check:
    Check: null
  Core:
    Id: CDISC.SDTMIG.CG0373
    Status: Draft
    Version: '1'
  Description: Trigger error when Dataset present in study with DOMAIN not equal to
    SUPP--.RDOMAIN
  Executability: null
  Outcome:
    Message: Dataset present in study with DOMAIN not equal to SUPP--.RDOMAIN
  Rule_Type: Record Data
  Scope:
    Classes:
      Include:
      - ALL
    Domains:
      Include:
      - ALL
  Sensitivity: Record

```

**Comment by htu** [comment]
Here is the json for CG0373: 

```json
{
    "id": "abcffc09-b50f-46a2-bea0-0baba8d3e3c1",
    "created": "2021-11-06T09:44:41Z",
    "changed": "2023-03-15T16:53:41Z",
    "creator": {
        "id": "dd0f9aa3-68f9-4825-84a4-86c8303daaff"
    },
    "content": "changed: '2023-03-15T16:53:41Z'\ncontent: null\ncreated: '2021-11-06T09:44:41Z'\ncreator:\n  id: dd0f9aa3-68f9-4825-84a4-86c8303daaff\nid: abcffc09-b50f-46a2-bea0-0baba8d3e3c1\njson:\n  Authorities:\n  - Organization: CDISC\n    Standards:\n    - Name: SDTMIG\n      References:\n      - Citations:\n        - Cited_Guidance: There is a one-to-one correspondence between a domain dataset\n            and it's Supplemental Qualifier dataset by creating one SUPPQUAL for each\n            domain dataset. The single SUPPQUAL dataset option that was introduced\n            in SDTMIG v3.1.1 is now deprecated. The set of Supplemental Qualifiers\n            for each domain is included in a separate dataset with the name SUPP--\n            where '--' denotes the source domain which the supplemental Qualifiers\n            relate back to.\n          Document: IG v3.2\n          Item: ''\n          Section: 8.4.2\n        Origin: SDTM and SDTMIG Conformance Rules\n        Rule_Identifier:\n          Id: CG0373\n          Version: '1'\n        Version: '2.0'\n      Version: '3.2'\n    - Name: SDTMIG\n      References:\n      - Citations:\n        - Cited_Guidance: There is a one-to-one correspondence between a domain dataset\n            and its Supplemental Qualifier dataset. The single SUPPQUAL dataset option\n            that was introduced in SDTMIG v3.1 was deprecated. The set of Supplemental\n            Qualifiers for each domain is included in a separate dataset with the\n            name SUPP-- where \"--\" denotes the source domain which the Supplemental\n            Qualifiers relate back to.\n          Document: IG v3.3\n          Item: ''\n          Section: 8.4.2\n        Origin: SDTM and SDTMIG Conformance Rules\n        Rule_Identifier:\n          Id: CG0373\n          Version: '1'\n        Version: '2.0'\n      Version: '3.3'\n    - Name: SDTMIG\n      References:\n      - Citations:\n        - Cited_Guidance: \"There is a one-to-one correspondence between a domain dataset\\\n            \\ and it's Supplemental Qualifier dataset by creating one SUPPQUAL for\\\n            \\ each domain dataset. The single SUPPQUAL dataset option that was introduced\\\n            \\ in SDTMIG v3.1.1 is now deprecated.  The set of Supplemental Qualifiers\\\n            \\ for each domain is included in a separate dataset with the name SUPP--\\\n            \\ where \\u201C--\\u201C denotes the source domain which the supplemental\\\n            \\ Qualifiers relate back to.\"\n          Document: IG v3.2\n          Item: ''\n          Section: 8.4.2\n        Origin: SDTM and SDTMIG Conformance Rules\n        Rule_Identifier:\n          Id: CG0373\n          Version: '1'\n        Version: '2.0'\n      Version: '3.4'\n  Check:\n    Check: null\n  Core:\n    Id: CDISC.SDTMIG.CG0373\n    Status: Draft\n    Version: '1'\n  Description: Trigger error when Dataset present in study with DOMAIN not equal to\n    SUPP--.RDOMAIN\n  Executability: null\n  Outcome:\n    Message: Dataset present in study with DOMAIN not equal to SUPP--.RDOMAIN\n  Rule_Type: Record Data\n  Scope:\n    Classes:\n      Include:\n      - ALL\n    Domains:\n      Include:\n      - ALL\n  Sensitivity: Record\n",
    "json": {
        "Check": {
            "Check": null
        },
        "Core": {
            "Id": "CDISC.SDTMIG.CG0373",
            "Version": "1",
            "Status": "Draft"
        },
        "Description": "Trigger error when Dataset present in study with DOMAIN not equal to SUPP--.RDOMAIN",
        "Outcome": {
            "Message": "Dataset present in study with DOMAIN not equal to SUPP--.RDOMAIN"
        },
        "Rule_Type": "Record Data",
        "Sensitivity": "Record",
        "Authorities": [
            {
                "Organization": "CDISC",
                "Standards": [
                    {
                        "Name": "SDTMIG",
                        "Version": "3.2",
                        "References": [
                            {
                                "Origin": "SDTM and SDTMIG Conformance Rules",
                                "Rule_Identifier": {
                                    "Id": "CG0373",
                                    "Version": "1"
                                },
                                "Version": "2.0",
                                "Citations": [
                                    {
                                        "Cited_Guidance": "There is a one-to-one correspondence between a domain dataset and it's Supplemental Qualifier dataset by creating one SUPPQUAL for each domain dataset. The single SUPPQUAL dataset option that was introduced in SDTMIG v3.1.1 is now deprecated. The set of Supplemental Qualifiers for each domain is included in a separate dataset with the name SUPP-- where '--' denotes the source domain which the supplemental Qualifiers relate back to.",
                                        "Document": "IG v3.2",
                                        "Item": "",
                                        "Section": "8.4.2"
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "Name": "SDTMIG",
                        "Version": "3.3",
                        "References": [
                            {
                                "Origin": "SDTM and SDTMIG Conformance Rules",
                                "Rule_Identifier": {
                                    "Id": "CG0373",
                                    "Version": "1"
                                },
                                "Version": "2.0",
                                "Citations": [
                                    {
                                        "Cited_Guidance": "There is a one-to-one correspondence between a domain dataset and its Supplemental Qualifier dataset. The single SUPPQUAL dataset option that was introduced in SDTMIG v3.1 was deprecated. The set of Supplemental Qualifiers for each domain is included in a separate dataset with the name SUPP-- where \"--\" denotes the source domain which the Supplemental Qualifiers relate back to.",
                                        "Document": "IG v3.3",
                                        "Item": "",
                                        "Section": "8.4.2"
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "Name": "SDTMIG",
                        "Version": "3.4",
                        "References": [
                            {
                                "Origin": "SDTM and SDTMIG Conformance Rules",
                                "Rule_Identifier": {
                                    "Id": "CG0373",
                                    "Version": "1"
                                },
                                "Version": "2.0",
                                "Citations": [
                                    {
                                        "Cited_Guidance": "There is a one-to-one correspondence between a domain dataset and it's Supplemental Qualifier dataset by creating one SUPPQUAL for each domain dataset. The single SUPPQUAL dataset option that was introduced in SDTMIG v3.1.1 is now deprecated.  The set of Supplemental Qualifiers for each domain is included in a separate dataset with the name SUPP-- where \u201c--\u201c denotes the source domain which the supplemental Qualifiers relate back to.",
                                        "Document": "IG v3.2",
                                        "Item": "",
                                        "Section": "8.4.2"
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ],
        "Scope": {
            "Classes": {
                "Include": [
                    "ALL"
                ]
            },
            "Domains": {
                "Include": [
                    "ALL"
                ]
            }
        },
        "Executability": null
    }
}
```

**Comment by gerrycampion** [comment]
| Spreadsheet                         | YAML                                                                  | Note                                                    |
| ----------------------------------- | --------------------------------------------------------------------- | ------------------------------------------------------- |
| Rule ID                             | Authorities[0].Standards[0].References[0].Rule Identifier.Id          |                                                         |
| SDTMIG Version                      | Authorities[0].Standards[0].Version                                   |                                                         |
| Rule Version                        | Authorities[0].Standards[0].References[0].Rule Identifier.Version     |                                                         |
| Class                               | Scope.Classes.Include                                                 | Classes will need to be standardized and split by comma |
| Domain                              | Scope.Domains.Include                                                 | Domains will need to be split by comma                  |
| Variable                            | \# Variable:                                                          | Comment                                                 |
| Condition                           | \# Condition:                                                         | Comment                                                 |
| Rule                                | \# Rule:                                                              | Comment                                                 |
| Document                            | Authorities[0].Standards[0].References[0].Citations[0].Document       |                                                         |
| Section                             | Authorities[0].Standards[0].References[0].Citations[0].Section        |                                                         |
| Item                                | Authorities[0].Standards[0].References[0].Citations[0].Item           |                                                         |
| Cited Guidance                      | Authorities[0].Standards[0].References[0].Citations[0].Cited Guidance |                                                         |
| Release Notes                       |                                                                       | Does not map                                            |
| "SDTMIG"                            | Authorities[0].Standards[0].Name                                      | Constant                                                |
| "SDTM and SDTMIG Conformance Rules" | Authorities[0].Standards[0].References[0].Origin                      | Constant                                                |
| "2.0"                               | Authorities[0].Standards[0].References[0].Version                     | Constant                                                |
| "Draft"                             | Core.Status                                                           | Constant                                                |
| "1"                                 | Core.Version                                                          | Constant                                                |
| "Fully Executable"                  | Executability                                                         | Constant                                                |
| "CDISC"                  | Authorities[0].Organization | Constant                                                |


[SDTM_and_SDTMIG_Conformance_Rules_v2.0 annotations.xlsx](https://github.com/cdisc-org/rule-transformations/files/10983611/SDTM_and_SDTMIG_Conformance_Rules_v2.0.annotations.xlsx)

**Comment by gerrycampion** [comment]
@htu these look great. Some comments about your samples:
- For the yaml files, only the contents within the `json` property are required. The other properties are only required in the json file.
- The property names in the yaml file should not have underscores. The property names in the json file should have underscores.
- I recommend copying the sample yaml rule into the [rule editor](https://rule-editor.cdisc.org/). The schema will alert you of most of the structure issues.
- Variable, Condition, and Rule columns should be mapped to comments in the beginning of the YAML file (comments start with `#`) (see table above). These won't appear in the `json` property in the json file because json does not allow comments.
- I would like to see an example with different Class and Domain other than `ALL`
- If `Item` is empty, don't include the `Item` property for the citation
- Replace `Check: Check: null` with `Check: null`
- Don't add `Core.Id`
- `Description` and `Outcome.Message` - I'm curious how you are generating these?
- `Rule Type` and `Sensitivity` should be left `null`
- I noticed these samples include rules merged from multiple rows in the source spreadsheet. I was expecting to see a sample for each row in the spreadsheet. Then, a second step would merge the rules from multiple rows for each rule id and also merge them with the rule ids in the core database. Is this following a different strategy?

**Reply by htu** [reply]
@gerrycampion Thanks for providing those points. I will work on them.  Could you elaborate a little on this one: "The property names in the yaml file should not have underscores. The property names in the json file should have underscores." Or give an example?

**Reply by gerrycampion** [reply]
@htu Have a look at Rule Type (Rule_Type) and Output Variables (Output_Variables) in the yaml, the json.content, and the json.json below.
There is a function in rule-transformations to do the conversion:
https://github.com/cdisc-org/rule-transformations/blob/main/transformer/transformer.py#L35-L45

```yaml
Check:
  all:
    - name: --TPTREF
      operator: empty
    - name: --ELTM
      operator: non_empty
Core:
  Id: CORE-000028
  Version: '1'
  Status: Published
Description: Raise an error when --TPTREF is empty, but --ELTM is not empty
Outcome:
  Message: --TPTREF is empty and --ELTM is not empty
  Output Variables:
    - --TPTREF
    - --ELTM
Rule Type: Record Data
```

```json
{
    "id": "8e4ce5f6-5d7d-420c-887d-26c09b89b793",
    "changed": "2022-12-02T16:10:42.162Z",
    "content": "Check:\n  all:\n    - name: --TPTREF\n      operator: empty\n    - name: --ELTM\n      operator: non_empty\nCore:\n  Id: CORE-000028\n  Version: '1'\n  Status: Published\nDescription: Raise an error when --TPTREF is empty, but --ELTM is not empty\nOutcome:\n  Message: --TPTREF is empty and --ELTM is not empty\n  Output Variables:\n    - --TPTREF\n    - --ELTM\nRule Type: Record Data\nSensitivity: Record\nAuthorities:\n  - Organization: CDISC\n    Standards:\n      - Name: SDTMIG\n        Version: '3.4'\n        References:\n          - Origin: SDTM and SDTMIG Conformance Rules\n            Rule Identifier:\n              Id: CG0008\n              Version: '1'\n            Version: '2.0'\n            Citations:\n              - Cited Guidance: The interval of time between a planned time point\n                  and a fixed reference point, represented in a standardized character\n                  format. The fixed reference point is in --TPTREF.\n                Document: SDTM Model v2.0\n                Item: --ELTM\n                Section: Timing\n      - Name: SDTMIG\n        Version: '3.3'\n        References:\n          - Origin: SDTM and SDTMIG Conformance Rules\n            Rule Identifier:\n              Id: CG0008\n              Version: '1'\n            Version: '2.0'\n            Citations:\n              - Cited Guidance: Planned Elapsed time relative to a planned fixed reference\n                  (--TPTREF) such as \"Previous Dose\" or \"Previous Meal\". This variable\n                  is useful where there are repetitive measures. Not a clock time\n                  or a date/time variable, but an interval.   Format=ISO8601\n                Document: SDTM Model v1.7\n                Item: Table 2.2.5, --ELTM\n                Section: 2.2.5\n      - Name: SDTMIG\n        Version: '3.2'\n        References:\n          - Origin: SDTM and SDTMIG Conformance Rules\n            Rule Identifier:\n              Id: CG0008\n              Version: '1'\n            Version: '2.0'\n            Citations:\n              - Cited Guidance: Planned Elapsed time in ISO 8601 character format\n                  relative to a planned fixed reference (--TPTREF) such as \"Previous\n                  Dose\" or \"Previous Meal\".\n                Document: SDTM Model v1.4\n                Item: Table 2.2.5, --ELTM\n                Section: 2.2.5\nScope:\n  Classes:\n    Include:\n      - ALL\n  Domains:\n    Include:\n      - ALL\n",
    "created": "2021-09-29T22:40:39Z",
    "creator": {
        "id": "e7bbd139-9a5c-4b86-859e-e4854e7724fe"
    },
    "json": {
        "Check": {
            "all": [
                {
                    "name": "--TPTREF",
                    "operator": "empty"
                },
                {
                    "name": "--ELTM",
                    "operator": "non_empty"
                }
            ]
        },
        "Core": {
            "Id": "CORE-000028",
            "Version": "1",
            "Status": "Published"
        },
        "Description": "Raise an error when --TPTREF is empty, but --ELTM is not empty",
        "Outcome": {
            "Message": "--TPTREF is empty and --ELTM is not empty",
            "Output_Variables": [
                "--TPTREF",
                "--ELTM"
            ]
        },
        "Rule_Type": "Record Data"
}
```

**Comment by gerrycampion** [comment]
Mappings from Class to Classes: Include:
ALL - ALL
EVT - EVENTS
FND - FINDINGS
INT - INTERVENTIONS
SPC - SPECIAL PURPOSE
TDM - TRIAL DESIGN

Mappings from Class, Domain to Classes: Include:
FND, FA - FINDINGS ABOUT

Mappings from Class to Domains:
AP - Domains: Include: AP--

NOT (***) in Class or Domain should be mapped to Exclude: instead of Include:

No Mapping - RELATIONSHIP
No Mapping - STUDY REFERENCE

**Reply by htu** [reply]
Gerry, thanks for the Class and Domain mapping! It seems that AP = "ASSOCIATED PERSONS" based on CG0159 ~ CG0161. Could you confirm this?

**Reply by htu** [reply]
It seems that CG0365~CG0367 follows the mapping that you suggested. These three are published. Here are the status for those records: 
[Class Domain Mapping.xlsx](https://github.com/cdisc-org/rule-transformations/files/11051721/Class.Domain.Mapping.xlsx)

**Reply by htu** [reply]
It seems that there is no consistency in terms of interpreting the mapping. Please see CG0367 (published): 
 "Scope": {
            "Classes": {
                "Include": [
                    "SPECIAL-PURPOSE"
                ]
            },
            "Domains": {
                "Exclude": [
                    "DM"
                ]
            }
        }

**Reply by gerrycampion** [reply]
@htu 
I would map how I originally mentioned as Domain AP--. The reason is because AP is not technically a class as far as I can tell. It is a type of domain that can take on other General Observation Classes.
The fact that the published rules are using AP-- wildcard confirms this.

CG0367 contains a bug. `SPECIAL-PURPOSE` should be `SPECIAL PURPOSE`. This is an artifact of a transformation that converted the old classes to new classes by capitalizing. Special-Purpose had a hyphen which was missed and I will need to fix these.

**Reply by gerrycampion** [reply]
FYI, I went through and fixed the SPECIAL-PURPOSE hyphens in prod

**Reply by gerrycampion** [reply]
For 367, I see you were talking about Special Purpose vs AP. I don't know why the rule was written this way. It should be written using Class: ALL, Domain: AP--
This is probably a mistake for this rule and we should see that in your merge report.

**Comment by gerrycampion** [comment]
For reference, the CT list that has the class names:
https://library.cdisc.org/browser/#/mdr/ct/2022-12-16/packages/define-xmlct-2022-12-16/codelists/C103329

**Reply by htu** [reply]
@gerrycampion could you copy the prod to the dev so that I can grab the changes that you made? Thanks!

**Reply by gerrycampion** [reply]
@htu I copied these

**Comment by htu** [comment]
I tested a few on existing rules and it merges citations correctly and passed the rule test. Here is CG0180:

**Comment by htu** [comment]
```YAML
# Variable: LBORNRLO
# Condition: LBORRES ^= continuous measurement
# Rule: LBORNRLO = null
Core:
  Id: CDISC.SDTMIG.CG0180
  Version: '1'
  Status: Draft
Description: Raise an error when LBORRES ^= continuous measurement and LBORNRLO is
  not empty.
Outcome:
  Message: LBORRES is contnot inuous measurement and LBORNRLO not equal to null
Rule Type: Record Data
Sensitivity: Record
Authorities:
  - Organization: CDISC
    Standards:
      - Name: SDTMIG
        Version: '3.2'
        References:
          - Origin: SDTM and SDTMIG Conformance Rules
            Rule Identifier:
              Id: CG0180
              Version: '1'
            Version: '2.0'
            Citations:
              - Cited Guidance: Lower end of reference range for continuous measurements
                  in original units. Should be populated only for continuous results.
                Document: IG v3.2
                Item: Specification
                Section: '6.3'
      - Name: SDTMIG
        Version: '3.3'
        References:
          - Origin: SDTM and SDTMIG Conformance Rules
            Rule Identifier:
              Id: CG0180
              Version: '1'
            Version: '2.0'
            Citations:
              - Cited Guidance: Lower end of reference range for continuous measurements
                  in original units. Should be populated only for continuous results.
                Document: IG v3.3
                Item: Specification
                Section: 6.3.6
      - Name: SDTMIG
        Version: '3.4'
        References:
          - Origin: SDTM and SDTMIG Conformance Rules
            Rule Identifier:
              Id: CG0180
              Version: '1'
            Version: '2.0'
            Citations:
              - Cited Guidance: Lower end of reference range for continuous measurements
                  for LBSTRESC/LBSTRESN in standardized units. Should be populated
                  only for continuous results.
                Document: SDTMIG v3.4
                Item: Specification
                Section: 6.3.5.6
Scope:
  Classes:
    Include:
      - FINDINGS
  Domains:
    Include:
      - LB
Executability: Partially Executable
Check:
  all:
    - name: LBORRES
      operator: non_empty
    - name: LBORNRLO
      operator: non_empty
```

**Comment by htu** [comment]
Here is a new one:
```YAML
# Variable: GEN
# Condition: Variable Core Status = Required
# Rule: Variable present in dataset and ^= null
Core:
  Id: CDISC.SDTMIG.CG0014
  Version: '1'
  Status: Draft
Description: Trigger error when Variable Core Status not equal to Required and Variable
  present not in dataset and is null
Outcome:
  Message: Variable Core Status not equal to Required and Variable present not in
    dataset and is null
Rule Type: Record Data
Sensitivity: Variable
Authorities:
  - Organization: CDISC
    Standards:
      - Name: SDTMIG
        Version: '3.2'
        References:
          - Origin: SDTM and SDTMIG Conformance Rules
            Rule Identifier:
              Id: CG0014
              Version: '1'
            Version: '2.0'
            Citations:
              - Cited Guidance: Required variables must always be included in the
                  dataset and cannot be null for any record.
                Document: IG v3.2
                Section: 4.1.1.5
      - Name: SDTMIG
        Version: '3.3'
        References:
          - Origin: SDTM and SDTMIG Conformance Rules
            Rule Identifier:
              Id: CG0014
              Version: '1'
            Version: '2.0'
            Citations:
              - Cited Guidance: Required variables must always be included in the
                  dataset and cannot be null for any record.
                Document: IG v3.3
                Section: 4.1.5
      - Name: SDTMIG
        Version: '3.4'
        References:
          - Origin: SDTM and SDTMIG Conformance Rules
            Rule Identifier:
              Id: CG0014
              Version: '1'
            Version: '2.0'
            Citations:
              - Cited Guidance: Required variables must always be included in the
                  dataset and cannot be null for any record.
                Document: IG v3.4
                Section: 4.1.5
Scope:
  Classes:
    Include:
      - ALL
  Domains:
    Include:
      - ALL
Executability: Partially Executable
Check:
  all: []

```

**Comment by htu** [comment]
This is a non executable CG0196 after running through the rule builder program: 
```YAML
# Variable: PEORRES
# Condition: PEORRES ^= null and no abnormal findings
# Rule: PEORRES = 'NORMAL'
Core:
  Id: CDISC.SDTMIG.CG0196 (NOT EXECUTABLE)
  Version: '1'
  Status: Draft
Description: Trigger error when PEORRES is null and no abnormal fnot indnot ings and
  PEORRES not equal to 'NORMAL'
Outcome:
  Message: PEORRES is null and no abnormal fnot indnot ings and PEORRES not equal
    to 'NORMAL'
Rule Type: Record Data
Sensitivity: Record
Authorities:
  - Organization: CDISC
    Standards:
      - Name: SDTMIG
        Version: '3.2'
        References:
          - Origin: SDTM and SDTMIG Conformance Rules
            Rule Identifier:
              Id: CG0196
              Version: '1'
            Version: '2.0'
            Citations:
              - Cited Guidance: Text description of any abnormal findings. If the
                  examination was completed and there were no abnormal findings, the
                  value should be NORMAL.
                Document: IG v3.2
                Section: '6.3'
      - Name: SDTMIG
        Version: '3.3'
        References:
          - Origin: SDTM and SDTMIG Conformance Rules
            Rule Identifier:
              Id: CG0196
              Version: '1'
            Version: '2.0'
            Citations:
              - Cited Guidance: Text description of any abnormal findings. If the
                  examination was completed and there were no abnormal findings, the
                  value should be NORMAL.
                Document: IG v3.3
                Section: 6.3.12
      - Name: SDTMIG
        Version: '3.4'
        References:
          - Origin: SDTM and SDTMIG Conformance Rules
            Rule Identifier:
              Id: CG0196
              Version: '1'
            Version: '2.0'
            Citations:
              - Cited Guidance: If the examination was completed and there were no
                  abnormal findings, the value should be "NORMAL".
                Document: IG v3.4
                Item: Specification
                Section: 6.3.8
Scope:
  Classes:
    Include:
      - FINDINGS
  Domains:
    Include:
      - PE
Executability: Partially Executable
Check:
  all: []
```
